site_name: Cloudsplaining
#theme: readthedocs
#use_directory_urls: false
site_url: https://cloudsplaining.readthedocs.io/
repo_url: https://github.com/salesforce/cloudsplaining
theme: material
use_directory_urls: true
markdown_extensions:
    - codehilite
    - tables
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - cloudsplaining/
nav:
  - "<b>Home</b>": 'index.md'
  - "<b>User Guide</b>":
    - Introduction: 'user-guide/overview.md'
    - Installation: 'user-guide/installation.md'
    - Downloading Account IAM Details: 'user-guide/download.md'
    - Creating an Exclusions File: 'user-guide/create-exclusions-file.md'
    - Scanning Account IAM Details: 'user-guide/scan-account.md'
    - Scanning a single policy: 'user-guide/scan-policy-file.md'
    - Troubleshooting: 'user-guide/troubleshooting.md'

  - "<b>Report Contents</b>":
    - Overview: 'report/overview.md'
    - Triage: 'report/triage.md'
    - Remediation: 'report/remediation.md'
    - Validation: 'report/validation.md'

  - "<b>Glossary</b>":
    - Privilege Escalation: 'glossary/privilege-escalation.md'
    - Resource Exposure: 'glossary/resource-exposure.md'
    - Data Exfiltration: 'glossary/data-exfiltration.md'
    - Credentials Exposure: 'glossary/credentials-exposure.md'
    - Infrastructure Modification: 'glossary/infrastructure-modification.md'
    - Service Wildcard: 'glossary/service-wildcard.md'
    - Roles Assumable by Compute Service: 'glossary/roles-assumable-by-compute-service.md'
    - Trust Policy: 'glossary/trust-policy.md'

  - "<b>Contributing</b>":
    - Contributing: 'contributing/contributing.md'
    - Documentation: 'contributing/documentation.md'
    - Python: 'contributing/python.md'
    - JavaScript: 'contributing/javascript.md'
    - Testing: 'contributing/testing.md'
    - Report Generation: 'contributing/report.md'
    - Versioning: 'contributing/versioning.md'

  - "<b>Appendices</b>":
    - FAQ: 'appendices/faq.md'
    - Comparison to other tools: 'appendices/comparison-to-other-tools.md'
    - Jira Ticket Automation: 'appendices/jira-ticket-automation.md'
