name: security

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: detect secrets
        uses: trufflesecurity/trufflehog@6bd2d14f7a4bc1e569fa3550efa7ec632a4fa67b # v3.94.2
        with:
          extra_args: "--exclude_paths .github/exclude-patterns.txt --max_depth=1"
