name: security

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: detect secrets
        uses: trufflesecurity/trufflehog@20652fbbdefffcdaa493a5bf57ab2ac6b1db715b # v3.97.1
        with:
          extra_args: "--exclude_paths .github/exclude-patterns.txt --max_depth=1"
